id: P000494
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-16 15:42:52.418408
source_metadata:
  id: bdr:W8LS20585
  title: གསར་བརྗེའི་རྒན་རབས་པ་བདུན་གྱི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    0ea91cd98b574cb7bf716932cfd9de2d:
      image_group_id: I8LS20587
      title: Volume 1 of gsar bar+j+je'i rgan rabs pa bdun gi gtam rgyud/
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
